version: "3.3"

services:
  mysql_db:
    image: mysql:5.7
    container_name: db-docker_mysql
    networks:
      - network
    volumes:
      - mysql_sample:/var/lib/mysql
      - ./mySql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    expose:
      - 3306

  postgres_db:
    image: postgres:latest
    container_name: db-docker_postgres
    networks:
      - network
    volumes:
      - postgres_sample:/var/lib/postgresql/data
      - ./pgSql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - 5432

  mssql_db:
    image: mcr.microsoft.com/mssql/server
    container_name: db-docker_mssql
    networks:
      - network
    volumes:
      - mssql_sample:/var/opt/mssql
      - ./msSql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      SA_PASSWORD: passw0RD
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    expose:
      - 1433

volumes:
  mysql_sample:
  postgres_sample:
  mssql_sample: 

networks:
    network:
      driver: bridge
